CREATE TABLE FLUXO_CAIXA(
INT_ID_FLUXO INTEGER IDENTITY,
INT_ID_ORG INTEGER NOT NULL,
STR_TIPO_FLUXO VARCHAR(10) NOT NULL,
STR_DESCRICAO_FLUXO VARCHAR(100) NOT NULL,
STR_VALOR_FLUXO VARCHAR(100) NOT NULL,
DT_DATA_FLUXO DATETIME NOT NULL DEFAULT GETDATE(),
PRIMARY KEY (INT_ID_FLUXO),
FOREIGN KEY (INT_ID_ORG) REFERENCES ORGANIZACAO (INT_ID_ORG)
)

SELECT f.INT_ID_FLUXO ID, o.str_nome_org Empresa,f.STR_VALOR_FLUXO Valor, f.STR_DESCRICAO_FLUXo 'Descrição' ,f.STR_TIPO_FLUXO Tipo,
f.DT_DATA_FLUXO Data
from FLUXO_CAIXA f,ORGANIZACAO o  where o.int_id_org = f.INT_ID_ORG

select * from ORGANIZACAO
update ORGANIZACAO set str_nome_org = 'JorgeConstruções' where int_id_org = 6
insert into FLUXO_CAIXA values(6,'Entrada','Taxa de Cadastro','R$ 3.000,00',getdate())